
# i=5
# while i>=1:
#    b=5
#    while b>=1:
#        print(i,end=" ")
#        b=b-1
#    print()
#    i=i-1
    

# i=0
# while i<26:
#     print(chr(65+i))
#     i=i+1
   
# i=0
# while i<26:
#     k=0
#     while k<=i:
#         print(chr(65+i),end=" ")
#         k=k+1
#     print("")
#     i=i+1



# i=0
# while i<6:
#     k=0
#     while k<6-i:
#         print(chr(65+i),end=" ")
#         k=k+1
#     print("")
#     i=i+1

i=0
while i<6:
    k=0
    while k<6+i:
        print(" ",chr(65+i),end="")
        k=k-1
    print("")
    i=i+1